In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

### One Hot Representation 

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1604, 7864, 8236, 7270], [1604, 7864, 8236, 3168], [1604, 4065, 8236, 9311], [5444, 494, 6042, 1810, 4059], [5444, 494, 6042, 1810, 7686], [7363, 1604, 6406, 8236, 808], [1774, 4731, 8434, 1810]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8 ## >= max sentance length
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1604 7864 8236 7270]
 [   0    0    0    0 1604 7864 8236 3168]
 [   0    0    0    0 1604 4065 8236 9311]
 [   0    0    0 5444  494 6042 1810 4059]
 [   0    0    0 5444  494 6042 1810 7686]
 [   0    0    0 7363 1604 6406 8236  808]
 [   0    0    0    0 1774 4731 8434 1810]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 1604, 7864, 8236, 7270])

In [14]:
print(model.predict(embedded_docs)[0]) 
### gives vector representation in dimention=dim(here 10) for each items in vocabulary of size=voc_size(here 10000) 

1/1 [==============================] - 0s 53ms/step
[[ 0.02619953  0.04394     0.02467651 -0.04673129  0.01295331  0.01798154
   0.03930068 -0.01477871  0.04706145 -0.01868732]
 [ 0.02619953  0.04394     0.02467651 -0.04673129  0.01295331  0.01798154
   0.03930068 -0.01477871  0.04706145 -0.01868732]
 [ 0.02619953  0.04394     0.02467651 -0.04673129  0.01295331  0.01798154
   0.03930068 -0.01477871  0.04706145 -0.01868732]
 [ 0.02619953  0.04394     0.02467651 -0.04673129  0.01295331  0.01798154
   0.03930068 -0.01477871  0.04706145 -0.01868732]
 [-0.04823275  0.02447525 -0.03171575 -0.03107835  0.03218831 -0.00806423
   0.02194471  0.00789387  0.01642657 -0.02889779]
 [ 0.04302508 -0.0069051  -0.01450934  0.00994004 -0.01741122  0.01368828
  -0.03374849 -0.01791107  0.03531995  0.003983  ]
 [ 0.01577634  0.01414864  0.03125742  0.0178487  -0.02070466 -0.00861762
  -0.04013959 -0.00046014 -0.04206699 -0.03848245]
 [-0.04218072 -0.01164439  0.04579506 -0.04901624 -0.02699531 -0.00412743

In [12]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 192ms/step
[[[ 2.61995308e-02  4.39399965e-02  2.46765055e-02 -4.67312932e-02
    1.29533075e-02  1.79815404e-02  3.93006839e-02 -1.47787109e-02
    4.70614471e-02 -1.86873190e-02]
  [ 2.61995308e-02  4.39399965e-02  2.46765055e-02 -4.67312932e-02
    1.29533075e-02  1.79815404e-02  3.93006839e-02 -1.47787109e-02
    4.70614471e-02 -1.86873190e-02]
  [ 2.61995308e-02  4.39399965e-02  2.46765055e-02 -4.67312932e-02
    1.29533075e-02  1.79815404e-02  3.93006839e-02 -1.47787109e-02
    4.70614471e-02 -1.86873190e-02]
  [ 2.61995308e-02  4.39399965e-02  2.46765055e-02 -4.67312932e-02
    1.29533075e-02  1.79815404e-02  3.93006839e-02 -1.47787109e-02
    4.70614471e-02 -1.86873190e-02]
  [-4.82327454e-02  2.44752504e-02 -3.17157507e-02 -3.10783517e-02
    3.21883075e-02 -8.06423277e-03  2.19447128e-02  7.89387152e-03
    1.64265744e-02 -2.88977865e-02]
  [ 4.30250801e-02 -6.90510124e-03 -1.45093426e-02  9.94003937e-03
   -1.74112208e-02  1.36882775